spring.application.name=demo
logging.level.org.springframework.boot.autoconfigure=DEBUG


# Tells H2 to run completely inside memory (mem)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatically creates tables from your Java Entities
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update



# Enable the H2 console UI
spring.h2.console.enabled=true

# Custom path to access the console (Default is /h2-console)
spring.h2.console.path=/h2-console